### ISSUE TITLE
Error in fetching BS 202000

### ISSUE THREAD

**Issue by kwkwan** [relaton/relaton-bsi#2]
When I include this line in metanorma references

`* [[[BS202000,BS 202000:2020]]], _Standardization management system_`

this error will appear

```
[relaton] BS 202000 does not have a recognised prefix: CN, IEC, IETF, ISO, ITU, NIST, OGC, CC, OMG, UN, W3C, IEEE, IHO, BIPM, ECMA, CIE, BSI, CEN.
See https://github.com/relaton/relaton/ for instructions on prefixing and wrapping document identifiers to disambiguate them.
```

**Comment by andrew2net** [comment]
First: We need to use prefixes. It's necessary for relaton to route requests to appropriate flavor gem. For the relaton-bsi the prefix is "BSI", so the reference should be "BSI BS 202000:2020"
Second: While testing the reference I've bumped into an issue with multiple ICS codes. The issue is solved in the last release. Please update this gem to the new 1.8.2 version.

**Comment by ronaldtse** [comment]
We currently have two types of notations:

1. "ISO XXX", "IEC XXX". 
2. "NIST SP XXX", "IETF RFC XXX".

NIST/IETF is prefixed with NIST/IETF for two reasons: distinguishing the organization and the publisher. But this makes sense because they are used this way.

The notation "BSI BS XXX" and "BSI PD XXX" do not actually make sense in this context because the document is never cited as "BSI BS XXX", it is always "BS XXX". I don't know whether we will run into future issues, but the "BS XXX" and "PD XXX" predate ISO, they are one of the oldest standards identification scheme.

Can you help allow "BS XXX" and "PD XXX" so that they are registered by Relaton-BSI?

Do remember there are also documents like "BS ISO 44001" and "PD ISO/TR 44000" and we should ensure they work.

Thanks!

**Comment by andrew2net** [comment]
@ronaldtse ok, I got, will add `BS` and `PD` to allowed prefixes for the relaton-bsi

**Comment by ronaldtse** [comment]
Thanks @andrew2net !

After adding these prefixes, can you help update relaton.org to show a list of all the supported prefixes (and where they link to)?
